version: '3.2'
services:

#minio storage instance
  storage:
    image: minio/minio
    ports:
     - target: 9000
       published: 9000
       protocol: tcp
       mode: host
    expose:
      - "9000"
    deploy:
      mode: global
      labels:
        feature.description: "Storage"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    command: server /data
#    healthcheck:
 #     test: ["CMD", "curl", "-f", "http://localhost:3000/minio/health/live"]
  #    interval: 30s
    #  timeout: 20s
      #retries: 3

